### ISSUE TITLE
include NAMD dataset

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemtest#17]
Data set for a https://github.com/alchemistry/alchemlyb/issues/7 NAMD parser.

- [x] add description in reST (include paper citation if appropriate)
- [x] compress files
- [x] add license (see [contributing datasets](https://github.com/alchemistry/alchemtest/wiki/contributing))
- [x] add entry to the reST files in the docs to reference the data set

**Comment by orbeckst** [comment]
@mrshirts @davidlmobley please sort out between your groups who wants to contribute test data. We can also include multiple datasets, we just need one to get started. 

I had assigned @mrshirts based on [today's discussion](https://github.com/alchemistry/alchemlyb/wiki/Minutes-2017-11-27) but obviously this is totally fluid. Just re-assign as necessary.

**Comment by orbeckst** [comment]
Potential NAMD FEP dataset:
* @mrshirts:  There's a data set from JC Gumbart for the Tyr->Ala example from the NAMD FEP tutorial that he gave me. The data files are at http://simbac.gatech.edu/forMichael/NAMD-FEP-tutorial-TYR2ALA.tgz  — (https://github.com/alchemistry/alchemlyb/issues/7#issuecomment-347399820)
*  @vtlim: If this is the same Tyr->Ala example as in this [tutorial](http://www.ks.uiuc.edu/Training/Tutorials/namd/FEP/tutorial-FEP.pdf), I've played around with some of their example [output](http://www.ks.uiuc.edu/Training/Tutorials/namd/FEP/FEP-tutorial-files.tar.gz) a while back. — (https://github.com/alchemistry/alchemlyb/issues/7#issuecomment-347410514)

**Comment by orbeckst** [comment]
@mrshirts @vtlim Have you been able to obtain permission from JC Gumbart to include NAMD FEP files under our [terms for contributing data sets](https://github.com/alchemistry/alchemtest/wiki/contributing)?

**Comment by mrshirts** [comment]
Yes, he has given permission.

**Comment by orbeckst** [comment]
Good news. Now, who is committing to adding the dataset? @mrshirts or @vtlim / @davidlmobley ?

**Comment by vtlim** [comment]
I can take care of it.
  

  
  

  
  
>

**Comment by orbeckst** [comment]
@vtlim thanks, please assign yourself to the issue. I sent you an invite to join the project.
