### ISSUE TITLE
GOMC parser does not load benzene files

### ISSUE THREAD

**Issue by msoroush** [alchemistry/alchemtest#35]
After compressing the free energy files, I forgot to change the file name in access.py

This line 
`data = sorted(glob(join(module_path, 'benzene', 'inWater', 'Free_Energy_BOX_0_PRODUCTION_*.dat')))`

must be changed to 

`data = sorted(glob(join(module_path, 'benzene', 'inWater', 'Free_Energy_BOX_0_PRODUCTION_*.dat.bz2')))`

**Comment by orbeckst** [comment]
Closed with PR #39
