### ISSUE TITLE
AMBER - more test file are needed

### ISSUE THREAD

**Issue by DrDomenicoMarson** [alchemistry/alchemtest#69]
To increase overall coverage, I should add some more files (at least two for now), as they are needed to test some part o the code that is not reached right now.

To do so I propose to create also a function to load single files, in this way it's much easier to prepare the single tests needed for everything we are missing right now. The same function could then be used to switch to more precise testing of invalid files, as reported in #65.

I already have a PR ready for this, which tests three missing branches in the AMBER parser (I already prepared also the PR with the test for alchemlyb, but this will have to wait until the merge of PR #240.

After these 3 tests are added only one line of AMBER parser will be left out.

**Comment by xiki-tempula** [comment]
Sorry, I was not reading this issue when I was closing https://github.com/alchemistry/alchemtest/issues/65. I finally understand what you are suggesting now. Initially, I thought that you just need a random file from a set but now I understand that each file in load_invalidfiles represents a special case and the naming of the invalid files is not the clearest thing in the world.
