### ISSUE TITLE
Do we have a possible undefined variable in `_version`?

### ISSUE THREAD

**Issue by DrDomenicoMarson** [alchemistry/alchemtest#70]
I noticed in `_version.py` we have at line 89 a variable `dispcmd` that is not defined inside of the `except` block, as it was defined inside the `try` block. Should we just move line 77 up before the `try` statement?

**Comment by orbeckst** [comment]
Don't bother, this file is auto-generated by versioneer. I can generate a newer version and see if it goes away.

**Comment by orbeckst** [comment]
Also, looking at the code, there's a high chance that `dispcmd` is defined before the try-block fails.
