### ISSUE TITLE
Used codecov with token

### ISSUE THREAD

**Issue by orbeckst** [alchemistry/alchemtest#85]
Try using codecov upload token to make codecov part of CI more robust.

**Comment by xiki-tempula** [comment]
@orbeckst Have you made any progress on this?

**Comment by orbeckst** [comment]
I added the secret into env variable `CODECOV` on GitHub. 

Do you have an example at hand how to use it for codecov in our ci.yml workflow?

**Comment by orbeckst** [comment]
found an example... please review @xiki-tempula
